In [1]:
import pandas as pd

In [15]:
df = pd.read_csv('네이버_재무제표_원본.csv', encoding='cp949')

In [21]:
df.drop(['Unnamed: 0', '종목코드'], axis=1, inplace=True)

In [17]:
df_div = pd.read_csv('네이버_재무제표데이터.xlsx - Sheet1.csv')

In [22]:
df_div.drop(['Unnamed: 0', '종목코드'], axis=1, inplace=True)

In [24]:
df

,종목명,PER,동일업종PER,추정PER,PBR,ROE,배당수익률,PER10이하주,PBR1이하주,ROE12이상주,동일업종대비PER하위주,PER대비추정PER하위주,배당수익률2이상주,2346만족,12346만족,123456만족
0,AJ네트웍스,4.16,10.83,NaN,0.84,0.20,3.96,1,1,1,1,0,1,1,1,0
1,AK홀딩스,NaN,8.54,NaN,0.43,NaN,1.02,0,1,0,0,0,0,0,0,0
2,BGF,7.45,6.23,NaN,0.31,0.04,2.16,1,1,0,0,0,1,0,0,0
3,BGF리테일,21.95,6.23,17.0,4.00,0.18,1.60,0,0,1,0,1,0,0,0,0
4,BNK금융지주,3.18,5.29,3.0,0.27,0.08,7.25,1,1,0,1,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
815,휴니드,9.88,31.16,NaN,0.90,0.09,NaN,1,1,0,1,0,0,0,0,0
816,휴비스,NaN,4.79,NaN,0.52,NaN,4.20,0,1,0,0,0,1,0,0,0
817,휴스틸,4.68,4.14,NaN,0.29,0.06,3.46,1,1,0,0,0,1,0,0,0
818,흥국화재,3.89,6.72,NaN,0.35,0.09,NaN,1,1,0,1,0,0,0,0,0
819,흥아해운,25.08,3.33,NaN,6.92,0.28,NaN,0,0,1,0,0,0,0,0,0

,종목명,PER,동일업종PER,추정PER,PBR,ROE,배당수익률,PER10이하주,PBR1이하주,ROE12이상주,동일업종대비PER하위주,PER대비추정PER하위주,배당수익률2이상주,2346만족,12346만족,123456만족
0,효성티앤씨,2.08,5.70,4.0,1.13,0.54,13.48,1,0,1,1,0,1,0,0,0
1,동양생명,3.51,4.82,6.0,0.31,0.09,10.35,1,1,0,1,0,1,0,0,0
2,NH투자증권,3.33,3.30,6.0,0.47,0.14,10.29,1,1,1,0,0,1,0,0,0
3,삼성증권,3.50,3.30,5.0,0.56,0.16,10.05,1,1,1,0,0,1,0,0,0
4,HD현대,NaN,13.02,6.0,0.69,NaN,9.02,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
815,효성중공업,9.76,20.95,8.0,0.60,0.06,NaN,1,1,0,1,1,0,0,0,0
816,효성화학,9.26,8.48,6.0,1.30,0.14,NaN,1,0,1,0,1,0,0,0,0
817,휴니드,9.88,31.16,NaN,0.90,0.09,NaN,1,1,0,1,0,0,0,0,0
818,흥국화재,3.89,6.72,NaN,0.35,0.09,NaN,1,1,0,1,0,0,0,0,0
819,흥아해운,25.08,3.33,NaN,6.92,0.28,NaN,0,0,1,0,0,0,0,0,0